PDP11/pdp11_vh.c
sigma/sigma_bugs.txt
sigma/sigma_dp.c
sigma/sigma_io.c
sigma/sigma_io_defs.h
sigma/sigma_mt.c

sigma: Clean compiler warning

---

HP3000/hp3000_defs.h
HP3000/hp3000_ds.c
sim_defs.h

Ken Rector, working with Bob found this discrepancy.

SCP: Fix details missed when merging update REGister macros from v3.12-2

---

PDP11/pdp11_cpu.c
PDP11/pdp11_cpumod.c
PDP11/pdp11_cpumod.h
PDP11/pdp11_defs.h
PDP11/pdp11_dz.c
PDP11/pdp11_fp.c
PDP11/pdp11_rh.c
PDP11/pdp11_vh.c
makefile
sigma/sigma_bugs.txt
sigma/sigma_coc.c

The latest from Bob and Ken and avoid noise about video in the v3 makefile (v3 has no video devices).

Supnik current

---

3B2/3b2_cpu.c
3B2/3b2_stddev.c

Change uint32_t into uint32 to fix issue #76.

---

sim_console.c

This allows Console output to work under Jenkins and if the output is redirected to a file.

SCP: On Windows fixed writing to Console when Console is file.

---

PDP11/pdp11_tv.c

Two small fixes for the TV device.

PDP11: Fixes for the Logo TV device.

---

VAX/vax750_stddev.c

This was missed in 3a95ba4b / #74

Fix another int32_t -> int32

---

AltairZ80/s100_hdc1001.c
AltairZ80/wd179x.c

Also a minor improvement in the debugging for wd179x.
FYI, @psco

AltairZ80: HDC-1001: Fix format.

---

PDP11/pdp11_tv.c

PDP11: Enforce limit on number of displays in TV device.

---

3B2/3b2_sys.c

The previous implementation of sim_load was riddled with little errors. This change fixes those errors, improves user feedback, and limits the allowable flags to '-r' and '-o'.

3b2: Improved sim_load procedure

---

BESM6/besm6_disk.c

This fixes a warning with some compilers.

BESM6: fix warning

---

PDP11/pdp11_rk.c

Please consider the following fix for source code typos

RK source consistency

---

.gitignore
PDP11/pdp11_rl.c
scp.c

The diffs are self-explanatory, I hope.

Three minor things to consider

---

sim_disk.c

This fixes issue #52, name conflict when building in MinGW.

DISK: rename CreateVirtualDisk

---

scp.c

Clean up variable expansion help

SCP: Add VM-specific messages to %TSTATUS% expansion

---

AltairZ80/altairz80_sio.c
AltairZ80/s100_adcs6.c
AltairZ80/wd179x.c

OASIS 5.6 Multiuser support for the Digitex 8200 machine comprised of an Advanced Digital Super-Six CPU card and ADC HDC-1001 hard disk controller.
Resources:
[OASIS Users Group Archive](https://github.com/hharte/OASIS_Users_Group) 
[Digitex 8200 Information](https://github.com/hharte/digitex) 
[OASIS 5.6 Distribution and config file](https://github.com/hharte/altairz80-packages/tree/main/dig_oasis56)
FYI, @psco

AltairZ80: Support OASIS 5.6 Multiuser

---

SEL32/README.md
SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_fltpt.c
SEL32/sel32_hsdp.c
SEL32/sel32_iop.c
SEL32/sel32_ipu.c
SEL32/sel32_lpr.c
SEL32/sel32_mfp.c
SEL32/sel32_mt.c
SEL32/sel32_scfi.c
SEL32/sel32_scsi.c
SEL32/sel32_sys.c
Visual Studio Projects/SEL32.vcproj
makefile

SEL32: Update makefile and SEL32.vsproj file to add IPU device.
SEL32: Update README.md file.
SEL32: Do a general code cleanup.

SEL32: Add IPU device support using pthreads on Linux and Windows.

---

sigma/sigma_coc.c

committed two fixes for sigma_coc.c. 
sigma: COC device, add LNORDER command option
sigma: COC device, handle transmit long, stop transmit and receive break

sigma: Coc fix

---

ND100/nd100_stddev.c

Original logic mixed up parameters and calibrated for 20000 ticks per second rather than 50.
Now leverage the sim_activate_after_abs() for precise microsecond tick delay and avoid explicit sim_cancel().

ND100: Fix CLK device setup and calibration

---

AltairZ80/altairz80_defs.h
AltairZ80/altairz80_sio.c
AltairZ80/i86.h
AltairZ80/m68k/m68kasm.c
AltairZ80/m68k/m68kcpu.c
AltairZ80/m68k/m68kfpu.c
AltairZ80/m68ksim.c
AltairZ80/mmd.c
AltairZ80/s100_dj2d.c
AltairZ80/s100_icom.c
AltairZ80/s100_jadedd.c
AltairZ80/s100_vdm1.c
sim_defs.h

This is purely code clean up, no change in functionality

AltairZ80: Remove Mac OS9 support, clean up function declarations

---

sigma/sigma_cpu.c
sigma/sigma_io.c

Added code to implement WAIT operation in sigma_cpu.c and correct the register returned for SIO, TIO, and other io instructions

sigma implement WAIT instruction

---

ND100/nd100_cpu.c
ND100/nd100_defs.h
ND100/nd100_floppy.c
ND100/nd100_mm.c
ND100/nd100_stddev.c
ND100/nd100_sys.c

Write MMS-1 support (Memory Management 1).    Also a lot of other bugfixes.
Can now boot the last test programs from floppy, and runs INSTRUCTION-C and PAGING-C without errors.

Add MMS-1 support.

---

PDP11/pdp11_rq.c

Now MV1 can boot Standalone Backup 4.0 from RX50.
See issue #215, #271, #277.

DISK: add RQDX1 model and make it default for MV1.

---

PDP11/pdp11_rr.c

It looks like disk controllers, which automatically update disk address (DA) after completion of I/O, are expected to do so even if there was no data transfer because of I/O errors. I was studying RSX-11's Error Logger documentation and examples are clearly offsetting disk addresses backwards by one when I/O errors are reported by the controller.
Since once the controller has found the DA-specified sector, the I/O begins regardless of the condition of the sector (bad or good data) or ability to transfer the contents between the disk and the memory.  If an error occurs (NXM, for instance) the operation would stop (with the error reported) at the end of the sector.  So if, for example, the bus address register had a bad address from the get-go, no data would be able to transfer at all, yet …

PDP11: RP11: Make sure to advance DA after every I/O

---

.travis/deps.sh

.travis/deps.sh will have an option that installs using pacman, which will make installation simpler for Arch users.

Added an option for Arch Linux to .travis/deps.sh

---

sigma/sigma_io.c
sigma/sigma_io_defs.h

sigma: Implement CM (Chaining Modifier) flag to  IOP simulator in sigma_io.c

sigma: Add chaining modifier flag to io

---

I650/i650_sys.c

See https://github.com/open-simh/simh/issues/382

Reduce stack usage

---

PDP10/ka10_pipanel.c
PDP10/kx10_cpu.c

I should not edit files on my Pi :-)

KA10: Removed tabs that got added by accident.

---

display/sim_ws.c

Compilation fix for at least Ubuntu 24.04

Compile fix: replaced Uint8 by uint8.

---

PDP11/pdp11_rr.c

Studying RSX11M source code I found out that the original RP11 controller (vs. -C and -E later versions) was still supported in the software, and notably UMD (User Mode Diagnostics) was still capable of handing it and dealing with its testing, even in much later OS versions (compared to when the original RP11 was phased out).
The change in this commit basically implements that flavor (which only supported the RP02 drives), and also makes a few minor fixes / cleanups for the device code, here and there.
The default mode for the RP11 controller remains the more widely used -C/-E version, but if so desired, it can be downgraded to support its predecessor with the "SET RR \<type\>" command now.

PDP11: RP11: Implement original RP11 controller flavor
