open-simh/simh

makefile, stub/readme.txt, stub/stub_cpu.c, stub/stub_defs.h, stub/stub_sys.c
This adds a new "simulator" called `stub`.  It's basically just an empty stub, but includes everything to build and run a simulator.
The intended purpose is to provide newcomers with an example, and a quicker route to get started writing a new simulator.
=> Sample stub simulator.

PDP11/pdp11_dup.c
This commit extends the existing DUP11 support to add simulation for a DPV11 in DDCMP mode.
It has been tested with DECnet-VAX Phase V, which has the only host driver I know of. Note
that you may see a few CRC errors logged with high traffic levels, these are due to a couple of
bugs in the VMS driver, for which I'm looking at developing a patch.
Regression testing has been done on the DUP11 on VMS, RSX and TOPS20, which all seemed to work
as well as previously.
=> QBus VAX and PDP11: Add support for DPV11 in DDCMP mode

scp.c
As reported and fixed by @al20878 in #9
=> SCP: Fix incorrect disk size reporting when t_addr is 32 bits

scp.c, sim_defs.h
- Rewrote get_rval, put_rval to support fields within arrays of structures
- REG "size" field now determines access size
- REG "maxval" field now determines maximum allowed value
Merge from v3.12
=> SCP: Updated REG macros and manipulation APIs - J. David Bryan v3.12 merge

PDP11/pdp11_dup.c
This commit extends the existing DUP11/DPV11 support to add support for HDLC framing. There
is no requirement to support bit/byte stuffing, so the aim is simply to encapsulate/decapsulate
the datalink frame provided by the host driver.
DDCMP has been regression tested on VMS, RSX and TOPS20, and the HDLC mode was developed
and tested with VAX/VMS DECnet Phase V, only using the HDLC datalink implementation.
In theory this support is sufficient to allow Phase IV/V P.S.I and even VMS/SNA to be used,
but these remain to be demonstrated.
=> QBus VAX and PDP11: Add support for HDLC framing to DUP11/DPV11

sim_video.c
This fixes issue #38 by setting the SDL_HINT_VIDEO_ALLOW_SCREENSAVER hint to 1, leaving the screen saver enabled.  SDL 2.0.2 had changed the default to disable the screen saver.
=> video: don't disable the screen saver

makefile, sim_ether.c
Pick up minor sim_ether.c and other minor makefile changes from cmake PR which are OK and independent of the rest of that PR.
=> Add makefile support for besm6 simulator build on current macOS systems

.travis/deps.sh, SIMH-V4-status.md, makefile, scp.c
This avoids infecting SIMH with the GPL license, since readline, very surprisingly, is GPL rather than LGPL.
Instead we use "editline" if available at build time.
=> simh ui: replace "readline" by "editline".

VAX/vax730_stddev.c, VAX/vax750_stddev.c, VAX/vax780_stddev.c, VAX/vax820_stddev.c, VAX/vax860_stddev.c
Take the version of the code from VAX/vax4nn_stddev.c, vax4xx_stddev.c and vax_stddev.c, and apply it to 730, 750, 780, 820 and 860.
If we can assume that clk_tps always remains 100, this can be simplified further.
=> Harmonize calibration code amongst VAXen.

PDP11/pdp11_cpu.c
Don't modify the CPU state when checking for physical address match on PC address breakpoints.  Reported and verified by Lars.
=> PDP11: Fix PC breakpoint check

PDP11/pdp11_cpu.c
The Small ITS timesharing system prefers this amount, leaving 32K free for mapping framebuffer data.
=> PDP11: Add option for 216K memory.

PDP11/pdp11_ng.c, display/ng.c, sim_video.c
Fix some bugs that were (probably) introduced by me.
- `vid_ready` in the SIM_DISPLAY struct can be used uninitialized.  This patch sets it to FALSE right away.
- SIMH would complain about an unrecognized event, mostly when multiple windows are in use.  That's because some events come without a valid windowID field, such as OPEN_WINDOW.
- The PDP11 "NG" device had the MATCH_CMD sense reversed.
- On closer reading of code using NG, it turns out that part of the state register is separate for each display.
=> Bug fixes for various video code.

BESM6/besm6_disk.c, BESM6/besm6_vu.c, makefile
This change allows CI builds to fail without detailed viewing of build output for gcc and clang builds (all modern compilers).  Thus forcing PR submitters to find these problems before PRs are merged.  This is done  by compiling with -Werror for these compilers.
We don't know how to do this for other compilers which may be able to use the makefile, so warnings there will still proceed to build successfully.
=> makefile: Make gcc and clang warnings fail builds on compile warnings

.github/workflows/build.yml, makefile
When building compiler optimized binaries with the gcc or clang compilers,
invoking GNU make with LTO=1 on the command line will cause the build
to use Link Time Optimization to maximally optimize the results.
Link Time Optimization can report errors which aren't otherwise detected
and will also take significantly longer to complete.
=> makefile: Add explicit LTO=1 make option to force gcc and clang LTO

PDP11/pdp11_dc.c, PDP11/pdp11_defs.h, PDP11/pdp11_dh.c, PDP11/pdp11_io_lib.c, PDP11/pdp11_mb.c, PDP11/pdp11_ng.c, PDP11/pdp11_sys.c, PDP11/pdp11_tv.c, Visual Studio Projects/PDP11.vcproj, display/ng.c, makefile
Includes the raster bitmap display controller and keyboards, and a stub for the bus-snooping memory debug device.  Plus some updates to reduce host CPU usage when SITS is running.
=> PDP11: Devices for SITS.

makefile
- Add missing BUILD_ROMS dependency to pdp11 simulator.  ROMs don't change often so this usually didn't matter, but it should be a dependency.
=> makefile: Make non debug builds with -O3 and LTO under gcc with -fwhole-program

sim_video.c
An event pulled from the queue after redraw has been handled needs to update the vptr pointer.  The problem will only be apparent if more than one window is open.
For example, the redraw event may be followed by a draw event for another window.  If vptr is not updated, vid_draw_region will clobber state in the wrong VID_DISPLAY structure and likely cause a crash.
=> VIDEO: Fix bug handling a redraw event.

.github/workflows/build.yml, S3/s3_sys.c, makefile
The CI build specifies OPTIMIZE=-O3 and runs with the default where warnings are converted to errors.
=> makefile: Add WARNINGS=ALLOWED make option and change default optimize to -O2

AltairZ80/i86_ops.c
Fixed a couple of bugs in the i86 CPU core.
Verified the REPE/REPNE segment override behavior against a real 80286 CPU, and also assembled MS-DOS 2.11 from source, as well as ran CP/M-86 and rebuilt the BIOS with success.
For the AAD instruction, the next byte was not fetched, causing the instruction sequence to be corrupted.  The fix is to align the behavior with AAM.
FYI @psco as discussed.
=> AltairZ80: i86: Fix bugs in REPE/REPNE as well as AAM instructions.

stub/stub_sys.c
Found with Debian clang version 15.0.3-2 and LTO=1.
=> Fix "non-void function does not return a value" warning

AltairZ80/altairz80_sio.c, AltairZ80/i86_decode.c
The AltairZ80 SIMH Pseudodevice provides a communication path between the host and guest operating system.  Information regarding file transfers is sent via the CP/M FCB at a fixed offset. 
To allow non-CP/M operating systems to read/write files to the host operating system, add a command that allows the guest OS to set the FCB address.
* Allows setting the FCB address used to send filenames between the host and guest operating systems.
* Increment the SIMH device version to SIMH005.
FYI, @psco
=> AltairZ80: SIO: Add setFCBAddressCmd to simh_dev.

AltairZ80/altairz80_sio.c
Fix warning introduced in PR#108, per @markpizz 's [comment](https://github.com/open-simh/simh/pull/108#issuecomment-1306232744).
FYI, @markpizz , @psco
=> AltairZ80: SIO: Fix warning for type mismatch.

I650/tests/i650_test.ini, PDP18B/tests/pdp9_test.ini, PDP8/tests/pdp8_test.ini, SEL32/tests/sel32_test.ini, VAX/tests/vax-diag_test.ini, sim_BuildROMs.c
If the Appveyor Windows CI build were working we'd have problems with these warnings.
The makefile build of BuildROMs doesn't use it as a normal make target but instead compiles and runs it under the covers without the CFLAGS values.  This is OK since it really isn't a target, but a pre-build sanity check to confirm the ROM inputs haven't changed.
=> BUILDROMS: Fix potential compiler warnings

AltairZ80/altairz80_sys.c, AltairZ80/s100_djhdc.c, AltairZ80/s100_tdd.c, Visual Studio Projects/AltairZ80.vcproj, makefile
The Tarbell double-density FDC is useful for running 86-DOS, [MS-DOS 1.25, 2.00, and 2.11](https://github.com/hharte/MS-DOS).
The Morrow DJ/DMA Hard Disk Controller works under MS-DOS 2.00 and 2.11.
Tests:
Compile with VS2008, VS2022, gcc (Linux), clang (MacOS.)
Test CP/M 2.2, CP/M-86, 86-DOS, ZEXALL.
FYI, @psco
=> AltairZ80: Add Tarbelll Double-Density FDC and Morrow DJ/DMA HDC

AltairZ80/s100_djhdc.c, AltairZ80/s100_tdd.c
This pull request addresses bug #116 and also removes an unused variable identified by @psco.
FYI, @pkoning2 , @bscottm
=> Fix AltairZ80: raise_scp300f_interrupt (not/un)defined #116

AltairZ80/altairz80_cpu.c, AltairZ80/altairz80_defs.h
```
sim> mem df00
DF00 C3 5C E2 C3 58 E2 7F 00 43 6F 70 79 72 69 67 68 .\..X...Copyrigh
DF10 74 20 31 39 37 39 20 28 63 29 20 62 79 20 44 69 t 1979 (c) by Di 
DF20 67 69 74 61 6C 20 52 65 73 65 61 72 63 68 20 20 gital Research
DF30 20 20 20 20 00 00 00 00 00 00 00 00 00 00 00 00     ............
DF40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
DF50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
DF60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ....s...ub...m..
DF70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ..I..tT...e.....
DF80 00 00 00 00 00 00 00 00 08 DF 00 00 5F 0E 02 C3 d....4...l.._0.r
DF90 05 00 C5 CD 8C DF C1 C9 3E 0D CD 92 DF 3E 0A C3 .d..M...>....>..
DFA0 92 DF 3E 20 C3 92 DF C5 CD 98 DF E1 7E B7 C8 23 ..> ..a.....~..#
DFB0 E5 CD …
```
=> AltairZ80: Add "MEM" and "REG" simulator-specific commands

AltairZ80/s100_pmmi.c
This PR changes the default DTR/RTS settings and follows CTS for socket connections.
=> AltairZ80: PMMI device DTR/RTS default changes and support for sockets

AltairZ80/altairz80_defs.h, AltairZ80/altairz80_sys.c, scp.c
AltairZ80 uses 0 for the VM-specific HLT instruction stop code.
SCP uses 0 to mean all errors ("ON ERROR").
The command "ON 0" will generate "%SIM-ERROR: Invalid argument: 0".
This PR changes the HALT stop code from 0 to 5.
=> AltairZ80: Fix CPU_HALT stop code conflict with SCPE_OK and "ON 0"

Intel-Systems/scelbi/scelbi_sys.c
Somehow this simulator got missed when this change was made for all other simulators.
=> SCELBI: Add missing array bound in sim_stop_messages array

PDP18B/tests/pdp9_test.ini, SEL32/tests/sel32_test.ini, VAX/tests/vax-diag_test.ini
Adjust the instruction limits for three simulators so they pass on Apple M1 systems.
=> PDP9 VAX SEL32: Adjust test limits

scp.c
In `sim_sanity_check_register_declarations` there is a variable `bytes` with no apparent use. Also the unused `udptr` should be removed.
=> SCP: Remove dead code in sim_sanity_check_register_declarations

PDP11/pdp11_rk.c, PDP11/pdp11_rl.c
=> PDP11: Fix RK11/RL11 byte/word count mismatch (and cyl upd in RK11)

AltairZ80/s100_adcs6.c
As pointed out by @markpizz , the only allowed macro to initialize UNIT structures is the UDATA macro.
Setting additional UNIT data structure items should be set through explicit initialization code in the DEVICE reset routine.
FYI, @psco , @markpizz
=> AltairZ80: ADCS6: Initialize extended UDATA in reset routine.

3B2/3b2_stddev.c, 3B2/3b2_timer.c
When the 3B2 simulator was set to allow idling, there was significant clock drift related to the primary timer unit. It turns out that the simulator was using `AIO_SET_INTERRUPT_LATENCY` and `sim_rtcn_tick_ack` incorrectly. They are not needed with the structure of system timers in the 3B2 architecture.
=> 3b2: Fix for clock drift when idling

PDP10/ka10_ch10.c, PDP10/ks10_ch11.c, PDP10/kx10_cpu.c, PDP10/kx10_defs.h, PDP10/kx10_imp.c, PDP10/kx10_mt.c
This patch includes fixes for Chaosnet interface and IMP interface to work correctly under ITS.  
Fixes for Quantum clock interrupt causing errors when KA was built under ITS.  
Cleanup of interrupt handling code.  
Start of changes for support of PiDP10 panel.   
Fixed TM10A to request first word at issue of write instruction.
=> KA10: Patchs for ITS and other things.

AltairZ80/altairz80_cpu.c, AltairZ80/s100_2sio.c
Summary of changes:
- AltairZ80 CPU: Add support for NMI interrupts. Reference for [Z80 NMI behavior](http://www.z80.info/zip/z80-documented.pdf).
- Fix potential NULL pointer deference in s100_2sio.
- Fix width of vectorInterrupt pseudo register.
Compiled with:
- VS 2022 17.4.4 (Debug and Release)
- VS 2008 (Debug and Release)
- MacOS (x64) clang-1400.0.29.202
- Linux gcc 10.2.1
Automated tests: SIMH running on Windows, Linux (ARM), MacOS (x64):
- [CompuPro CP/M-80](https://schorn.ch/cpm/zip/cpm86.zip)
- [CompuPro CP/M-86](https://schorn.ch/cpm/zip/cpm86.zip)
- [SCP 86-DOS](https://schorn.ch/cpm/zip/86dos.zip)
- [MS-DOS 2.11](https://github.com/hharte/altairz80-packages/tree/main/msdos211_test)
- [CompuPro CP/M-68K v1.3](https://github.com/hharte/altairz80-packages/tree/main/ccpm68k13) …
=> AltairZ80: Add NMI interrupt support

scp.c, sim_rev.h
With three simulators sharing a common heritage and name, it can get confusing when questions arise from the user community.
This edit changes the Minor version from 0 to 1 (e.g. V4.1) and adds "Open SIMH" to the banner and show version output.
=> Identify Open SIMH builds in version strings

AltairZ80/s100_adcs6.c
**Summary of change:**
* Resolve issue #164: Proper initialization of the ADCS6 unit data structure depended on the ADCS6 device being enabled.  In cases where the ADCS6 unit was not enabled, non-debug builds may crash on some host platforms depending on compiler/memory layout.
Thanks @markpizz for tracking this down and for the fix.
**Compiled with:**
* VS 2022 17.4.4 (Debug and Release)
* VS 2008 (Debug and Release)
* MacOS (x64) clang-1400.0.29.202
* Linux gcc 10.2.1
**Automated tests:**
SIMH running on Windows 10 (debug/release), Windows 11 (debug/release), Linux (ARM), MacOS (x64):
[CompuPro CP/M-80](https://schorn.ch/cpm/zip/cpm86.zip)
[CompuPro CP/M-86](https://schorn.ch/cpm/zip/cpm86.zip)
[SCP 86-DOS](https://schorn.ch/cpm/zip/86dos.zip)
[MS-DOS …
=> AltairZ80: ADCS6: Fix uninitialized unit structure

AltairZ80/altairz80_cpu.c
Used to initialize SCP timers to prevent problems during simulator startup when THROTTLE is being used.
```
/*
* This sequence of instructions is a mix that mimics
* a resonable instruction set that is a close estimate
* to the calibrated result.
*/
static const char *cpu_clock_precalibrate_commands[] = {
"-m 100 LXI H,200H",
"-m 103 MVI B,0",
"-m 105 DCR B",
"-m 106 MOV M,B",
"-m 107 INX H",
"-m 108 JNZ 0105H",
"-m 10B JMP 0100H",
"PC 100",
NULL};
```
=> AltairZ80: Add sim_clock_precalibrate_commands

SDS/sds_cr.c
SDS: reset cr_eor on disconnect. Caused algol compiler to hang
=> SDS:reset cr_eor on disconnect

sigma/sigma_coc.c, sigma/sigma_dk.c, sigma/sigma_dp.c, sigma/sigma_io.c, sigma/sigma_io_defs.h, sigma/sigma_lp.c, sigma/sigma_mt.c, sigma/sigma_pt.c, sigma/sigma_rad.c, sigma/sigma_tt.c
This corrects an error that caused SIO reject when SIO occured before a pending seek interrupt on a different device.
- Move the interrupt pending test from sigma_io.c into each device.
- Make the sigma_dp.c test a special case that looks for pending seek interrupts.
=> sigma: Correct recognition of pending DP seek interrupt.

PDP11/pdp11_dh.c
This fixes issue #201, using a fix proposed bu Bjoren Davis.
=> PDP11: Support byte write access to DHCSR.

AltairZ80/altairz80_cpu.c, AltairZ80/altairz80_hdsk.c, AltairZ80/altairz80_sio.c, AltairZ80/altairz80_sys.c, AltairZ80/flashwriter2.c, AltairZ80/i8272.c, AltairZ80/m68k/m68kfpu.c, AltairZ80/s100_disk3.c, AltairZ80/wd179x.c, Visual Studio Projects/AltairZ80.vcxproj, Visual Studio Projects/AltairZ80.vcxproj.filters, sim_imd.c
Summary of changes:
* Fix static code analysis issues in sim_imd.c.
* Fix static code analysis issues in Flashwriter and CompuPro Disk3.
Compiled with:
VS 2022 17.5.3 (Debug and Release)
VS 2008 (Debug and Release)
MacOS (x64) clang-1400.0.29.202
Linux gcc 10.2.1
Automated tests: SIMH running on Windows, Linux (ARM), MacOS (x64):
[CompuPro CP/M-80](https://schorn.ch/cpm/zip/cpm86.zip)
[CompuPro CP/M-86](https://schorn.ch/cpm/zip/cpm86.zip)
[SCP 86-DOS](https://schorn.ch/cpm/zip/86dos.zip)
[MS-DOS 2.11](https://github.com/hharte/altairz80-packages/tree/main/msdos211_test)
[CompuPro CP/M-68K v1.3](https://github.com/hharte/altairz80-packages/tree/main/ccpm68k13) (68000 and 68010 versions)
[CP/M-68K v1.2](https://schorn.ch/cpm/zip/cpm68k.zip)
[Advanced Digital Super-Six CP/M …
=> AltairZ80, sim_imd: Fix static code analysis warnings.

AltairZ80/s100_vdm1.c
Corrects video window aspect ratio
Corrects `d -m c mov m,b` SCP error
Changes default dirty flag from FALSE to TRUE
=> AltairZ80 VDM1: Corrects SCP error and video aspect ratio

sigma/sigma_bugs.txt, sigma/sigma_mt.c
sigma_mt.c - AIO must mask unit number before calling TDV status.
=> sigma: MT: AIO must mask unit number before calling TDV status.

scp.c, scp.h
- Fix improper get_yn() use in test library logic
Reported by Peter Schorn
=> SCP: Change declaration of get_yn() to have boolean argument and return value

3B2/3b2_cpu.c, 3B2/3b2_defs.h, 3B2/3b2_ports.c, 3B2/3b2_ports.h, 3B2/3b2_rev2_defs.h, 3B2/3b2_rev2_mmu.h, 3B2/3b2_rev2_sys.c, 3B2/3b2_rev3_mmu.c, 3B2/3b2_rev3_sys.c, 3B2/3b2_scsi.c
This change adds support for printing to an attached text file via the Centronics port of a simulated PORTS feature card. A new device named "LPT" has been added. See "help lpt" for documentation.
Additionally, there has been a fix to a bug in the SCSI tape boot implementation and a very minor bug fix to the Rev 3 MMU.
=> 3B2: LPT Device; MMU and SCSI fixes

3B2/3b2_timer.c
Under certain circumstances, the timer resolution in the Version 3 could become coarse enough that very short timer intervals would lead to an infinite loop of bus errors when running timer firmware diagnostics.
=> 3B2: Fix for diagnostics timer hang

sim_defs.h
Only SCP libraries should be including additional OS specific include files since they cover both:
1) Are responsible for platform specific details integrated into simh
support
and
2) Implement extended functionality optimally considering the proper
behaviors to cooperate with the simh event system and existing
capabilities.
Simulator code can optionally include any of these system include files:
<stddef.h>, <stdlib.h>, <stdio.h>, <stdarg.h>, <string.h>, <errno.h>.
<limits.h>, <ctype.h>, <math.h>, <setjmp.h>
Such inclusion will be redundant with what is already provided here by sim_defs.h.  Simulator code should include SCP provided include files:
"scp.h", "sim_card.h", "sim_console.h", "sim_disk.h", "sim_ether.h",
"sim_fio.h", "sim_imd.h", "sim_scsi.h", "sim_serial.h", "sim_tape.h", …
=> SCP: Include all simh supported system includes in sim_defs.h

Visual Studio Projects/Pre-Build-Event.cmd
Windows-build has been updated to solve #255.
This commit causes local builds (and CI ones) to update their local copy of the windows build components to build cleanly with Visual Studio 2022 v17.6.4
=> Visual Studio Projects: Force build to update to the latest windows-build

.github/workflows/cmake-builds.yml
VS installer's startup is not instantaneous and there's some lag in the CI/CD pipeline. Adjust strategy to wait for startup (20 seconds max) to make the script more robust. (Doesn't seem to get triggered, but that doesn't mean it won't happen in the future.)
Add the the following command line flags:
--force: Forces VS instance termination, if any are running.
(Unclear impact. Paranoia.)
--norestart: Delay reboot, if reboot needed. (Probable reason why
(Most likely reason why installs were incomplete.)
--installWhileDownloading: Self-explanitory. (Unclear impact.)
"Get-VSSetupInstance/Select-VSSetupInstance" will report a VS instance ID if successful, e.g.:
DEBUG: Get-VSSetupInstance/Select-VSSetupInstance
InstanceId          : 8d19910a
DisplayName         : Visual Studio Enterprise 2022 …
=> v141_xp: VS Installer whack-a-mole tournament

sim_disk.c
If the total sectors exceeds 127Gb this is not possible, but normal simh disks are smaller and the largest user settable size via RAUSER is just under 1Tb.  The excessive size case (>127Gb) will have a CHS of 0xFFFF10FF.
simh never cares about the CHS Disk Geometry value in the VHD footer data structure, but other applications which do care about the CHS value using the previously incorrect value as the capacity of the disk even though the Current Size indicated in the footer may have been larger.
Fixes #287
=> DISK: Fix VHD to Ensure that the CHS capacity exceeds the disk length

PDP11/CMakeLists.txt, PDP11/pdp11_defs.h, PDP11/pdp11_io_lib.c, PDP11/pdp11_rr.c, PDP11/pdp11_sys.c, Visual Studio Projects/PDP11.vcproj, Visual Studio Projects/PDP11.vcxproj, Visual Studio Projects/PDP11.vcxproj.filters, makefile
=> PDP11: RP11-C (RP02/03) disk implementation

PDP11/pdp11_ts.c
The BOOT command for this device was not correctly documented in HELP (appearing both supported and not) for PDP-11.
This patch fixes the issue and syncs HELP output with the actual code (by using the same `#if` conditional).
=> PDP11: TS11: Fix help output for BOOT command

PDP11/pdp11_rr.c
I have run the code thru XXDP and some other OS's and scenarios rigorously, and found discrepancies, which need to be addressed by this rather extensive patch.
1. Each drive must implement its own "drive status" register, to be able to track per-drive errors / conditions correctly;
2. Fixed `INT_SET()` /  `INT_CLR()` in `RPCS` write function (wrong order of the "`if`" conditions);
3. Some behavior was implemented not exactly how it was expected from the real hardware, such as:
a. Post-I/O register values in `RPDA` and `RPCA` (including the corner case of pack overflow);
b. I/O stacking, which wasn't mentioned in any available documentation, but only XXDP listings;
c. `RESET`/`IDLE` function must be accepted for a "busy" controller;
d. `HOME` function must always execute, even when "device …
=> PDP11: RP11: Major update after XXDP

PDP11/pdp11_cpumod.c
`17 777 740` - `17 777 742`, read-only error address registers, and `17 777 764`, a read-only System ID register,
are not handled in the `CPU70_wr()` routine, which means for these addresses the routine returns `NXM`, which then translates to "bus timeout" (no response to address), and then, as a result, trap to vector 4.
That is incorrect, IMO.
These locations are read-only yet the address gets decoded, and even though writing does not have any effect, the write routine for these addresses should return `SCPE_OK`.
This patch fixes the issue.
Background:
I was trying to run DEC/X11 diagnostic and, instead of getting the "`CMD>`" prompt, when started it was throwing a lot of VECTOR 4 errors for the following instruction, endlessly (only the simulator stop and reboot would help):
```
** …
```
=> PDP11: 11/70 read-only registers must not return NXM on write

.github/workflows/cmake-builds.yml
Clean up /usr/local/bin symlinks to /Library that prevents "brew update" from succeeding. The macOS 11 image has Python binaries symlinked into /usr/local/bin from /Library, which consequently sends `brew` into a build failure.
Not specific to the Github macos-11 image, inserted for macOS generally.
(Nudge: Please merge PR #286 and #149 as well.)
=> Remove files symlinked to /Library

sim_disk.c
This is the initial iteration of cleaning up simh of appending the "footers" to disk images:  it does not allow to emit any new "footers", yet it does not change the behavior as to how any existing "footers" are treated internally.  Also, even though sim_disk.c currently builds the "footer" for any attached disk container, with this patch, it is only kept in-memory, and never gets written to (appended / updated) the actual container.
To address #13 
Any existing "footer" already in the disk image, can be dropped with the "ZAP" command, and with this patch, it won't get reinstated.
=> DISK: Do not allow to emit any "footers"

PDP11/pdp11_rq.c
Added additional SDI MSCP devices (the ESE20 solid state disk, and ESE50 series of solid state disks).
Added RF35 to the drv_tab and drv_types tables, fixing an off-by-one error.
=> Additional SDI drives for MSCP emulation, minor RQ device bugfix

AltairZ80/sol20.c
The Sol-20 provides 1K RAM at C800. This was discovered to be missing when issuing a "SET CPU 24K" command. Without the CPU providing RAM at C800, the Sol-20 would not function. This PR corrects the problem by having the SOL20 device provide its own 1K RAM at C800.
=> ALTAIRZ80: Add 1K RAM to SOL20 device

sim_timer.c
SCP doesn't initially adjust timer calibrations if SET THROTTLE x/t type is enabled causing large delays in event dispatches. This PR runs the timers through the same calibration adjustment loop as other throttle types.
=> SCP: Adjust timer calibrations if SET THROTTLE x/t type is enabled

AltairZ80/altairz80_cpu.c
The MEM dump command would not display past SET CPU xK memory size. This prevented displaying ROMs or other RAM windows when a lower amount of memory was specified. This PR changes MEM to always display a minimum of a 64K regardless of main RAM size.
=> ALTAIRZ80: Fixes problem with MEM dump command

VAX/vax_xs.c, scp.c, sim_ether.c
SET NOASYNC is intended to disable asynchronous threads from interacting with the simulator event system.
The only cases where there asynchronous threads are:
1) Disks which are designed for asynchronous support using sim_disk.  The only case is the MSCP controller implemented by pdp11_rq (Device name RQ).
2) Tapes which are designed for asynchronous support using sim_tape.  The only case is the TMSCP controller implemented by pdp11_tq (Device name TQ).
3) Devices which use sim_ether to interface with Ethernet networks.  There are a number of these cases.
Prior to this change, SET NOASYNC only actually affected the RQ and TQ devices and had no effect on Ethernet devices.
=> ETHER: Make sure SET NOASYNC is effective for Ethernet devices

PDP8/pdp8_cpu.c
Fix suggested by David Gesswein in #342
=> PDP8: Fix missing clock pre-calibration instruction set due to typo

AltairZ80/altairz80_cpu.c
Changing the CPU type or MEMORY size/configuration causes memory resources mapped by other devices to be removed. This is not made clear by `HELP CPU` and the user has no feedback that this is happening.
This PR does the following:
1. `HELP SET CPU` now shows that `SET CPU MEMORY` requires a value.
2. Feedback is now provided if the value is omitted or not properly formatted.
3. Unmapped memory resources caused by a `SET CPU` command is now displayed on the SIMH console.
4. Adds a `SET CPU RESIZEMEMORY` command that resizes system memory without unmapping other device memory resources.
=> AltairZ80: Adds SET CPU RESIZEMEMORY and other

sim_card.c
Conversion from int to size_t cause the buffer shifting code to break.
=> SIM_CARD: Fixed issues caused by last commit to sim_card.c

cmake/cmake-builder.ps1
cmake/cmake-builder.ps1 added quotes to arguments that contained spaces so that arguments printed correctly for progress output. This introduced excess quotes that caused CMake (and likely other MS apps) confusion or argument misinterpretation.
Instead of CMake seeing a single "Visual Studio 17 2022", CMake was actually seeing "\"Visual Studio 17 2022\"".
This patch only adds the additional quotes when reporting progress. Otherwise, command line arguments are passed unmolested.
=> CMake: Reduce excess quoting

.github/workflows/build.yml, .github/workflows/cmake-builds.yml, .travis/deps.sh, scp.c
- Fix comma separator code segmentation fault: "ndigit - 3" can become a very large unsigned number for ndigit < 3.
- dir_cmd: Allocate WildName from heap to reduce stack pressure.
- Github CI/CD: Remnant symlink issue reappeared, afflicting the makefile-based build. For better or worse, the workaround is now dependent on specific Python versions that must be removed, unlinked and any remnant symlinks that HomeBrew decided it needed to install in /usr/local/bin. The Python upgrade is triggered by the sdl2_ttf package.
According to the Github image maintainers, this is an old, known issue in macOS images that originates inside of Homebrew.
=> SCP: sprint_val comma bug, GH: Remnant symlinks

AltairZ80/altairz80_sio.c
The `boot` command causes all devices to reset which removes the `SET SIO INTERRUPT` service routine from the SIMH event queue which disables interrupt processing. The user must escape back to the `simh>` prompt and `SET SIO INTERRUPT` again after boot. An example of the problem:
```
at dsk altdos.dsk
set sio interrupt
boot dsk
MEMORY SIZE? << Enter >>
INTERRUPTS? Y << Enter >>
HIGHEST DISK NUMBER? << interrupt never happens, program hangs >>
```
This PR has sio_reset put the SIO interrupt service routine back on the event queue if interrupts have been enabled with `SET SIO INTERRUPT`.
```
at dsk altdos.dsk
set sio interrupt
boot dsk
MEMORY SIZE? 
INTERRUPTS? Y
HIGHEST DISK NUMBER? 1
HOW MANY DISK FILES? 1
HOW MANY RANDOM FILES? 1
056943 BYTES AVAILABLE
DOS MONITOR VER 1.0
COPYRIGHT 1977 …
```
=> AltairZ80: Enable SIO interrupt service event after BOOT

sigma/sigma_bugs.txt, sigma/sigma_dk.c, sigma/sigma_dp.c, sigma/sigma_io.c, sigma/sigma_io_defs.h, sigma/sigma_mt.c
Fix three kinds of error in device modules.  Discovered while getting standalone System Exerciser to run.
IO: DVT_NOTDEV macro incorrect, Device mapping algorithm creates false dispatch points. This mapped Multi Unit Controller and Single Unit Controller to same device. 
DP, DP, MT, RAD:  Test for non-existent device returns wrong status. 
DP, DK, MT: TIO status should return non-operational for unattached device.
=> SIGMA: Bugfixes in various device modules

.github/workflows/build.yml, .github/workflows/cmake-builds.yml
Github upgraded Node.js from version 16 to version 20; Node.js drives the CI/CD pipelines. Github strongly recommends bumping the actions' version number from "@v3" to "@v4" and produces copious warning messages in the CI/CD "Annotations" pane for each submission.
=> Github CI/CD: Bump action version from v3 to v4.

Ibm1130/ibm1130_cpu.c, Ibm1130/ibm1130_cr.c, Ibm1130/ibm1130_gui.c
- Add the missing ibm1130.rc GUI resource file to the Windows build so that the GUI renders correctly.
- Add "TEST_ARGS" argument to CMake's add_simulator function so that the IBM 1130 simulator can pass to "-g" on the command line to disable the GUI when running RegisterSanityCheck, i.e.:
ibm1130 RegisterSanityCheck -g
This fixes an edge case Heisenbug encountered during Github CI/CD tests where ibm1130 appears to hang indefinitely on the Windows runners.
The cause is the GUI's Pump() thread function being prematurely terminated before all GUI resources are acquired: `RegisterSanityCheck` completes and starts terminating the simulator, which prejudiciously terminates the Pump() thread. The Pump() thread, in the meantime, can be terminated in the middle of resource acquisition due to …
=> IBM 1130: GUI resource file, RegSanityCheck fix

AltairZ80/CMakeLists.txt, AltairZ80/altairz80_sys.c, AltairZ80/s100_dazzler.c, Visual Studio Projects/AltairZ80.vcproj, Visual Studio Projects/AltairZ80.vcxproj, Visual Studio Projects/AltairZ80.vcxproj.filters, makefile, sim_video.c, sim_video.h
Adds Cromemco Dazzler and JS1 joystick devices
Adds vid_render_set_logical_size() to sim_video.c
Adds separate debug logging for Joystick to sim_video.c
`BOOT DAZZLER` will display a color pattern.
=> AltairZ80: Adds Cromemco DAZZLER and JS1 devices

AltairZ80/s100_jair.c
I was having problems with the JAIR device keeping up with received data at 57.6K.
This PR makes the following changes to the JAIR devices:
- Refactors the service routines into STAT, TX and RX units (thanks @markpizz)
- Adds a 128-byte input ring buffer
- Corrects a null pointer exception
- Adds overrun status bit implementation
- Replaces a tab with spaces
The simulator will now boot Mike Douglas' Serial CP/M, modified for the JAIR, over a serial port connected to the FDC+ serial server at 57.6K.
```
ALTAIR/IMSAI 8080 CPU BOARD BOOT LOADER - Josh Bensadon v2.6 May 30, 2024
INIT_FAT 
Init SD Type#1 ACMD41+MBR S Type06 PBR S VOL=JAIRCPM     SYS=FAT16   
<D> -SD Card Directory
<R> -RAM Test
<S> -Serial Boot
<V> -View Load
<1> -1.HEX
<2> -2.HEX
<3> -3.HEX
<4> -BIOS61K.HEX
<5> -BIOS.HEX
<6> …
```
=> AltairZ80: Changes to JAIR devices

VAX/CMakeLists.txt, VAX/vax820_defs.h, VAX/vax820_syslist.c, VAX/vax860_defs.h, VAX/vax860_syslist.c, Visual Studio Projects/VAX8200.vcproj, Visual Studio Projects/VAX8200.vcxproj, Visual Studio Projects/VAX8600.vcproj, Visual Studio Projects/VAX8600.vcxproj, makefile
The VAXstation 100 "unibus window" interface board should work with any Unibus VAX.
The updates are quite trivial... or did I miss anything?  VAX person, please review.
=> VAX: Add UW device to 8600 and 8200.

PDP11/pdp11_rr.c
Recent analysis of the 2.9BSD kernel revealed that RP11 was expected to interrupt on control RESET function if IE bit was also set.  Documentation was not very clear of the fact, saying in one place that RESET+GO does not interrupt (which is not contradictory with the above because it does not mention IE).
In other place, however, it says that IE always causes interrupt when DONE is asserted.  Thus, since RESET does assert DONE, an interrupt should be posted if IE is set.  The autoconfig binary from 2.9BSD uses this feature of RP11 to check the presence of the controller.
Formerly RESET was always clearing RPCS with DONE unconditionally, and that reset IE as well.  This patch makes sure that the IE bit is preserved, and if set, it posts an interrupt when RESET asserts DONE.
=> PDP11: RP11: Interrupt on IE+RESET+GO

AltairZ80/CMakeLists.txt, AltairZ80/altairz80_sys.c, AltairZ80/s100_tuart.c, Visual Studio Projects/AltairZ80.vcproj, Visual Studio Projects/AltairZ80.vcxproj, makefile
Adds the following devices to AltairZ80:
TUART0: Cromemco FDC controller TUART console port at I/O address 0x00.
TUART1: Cromemco TU-ART port A at I/O address 0x20.
TUART2: Cromemco TU-ART port B at I/I address 0x50.
These devices are fully TMXR capable.
=> AltairZ80: Adds Cromemco TUART devices

Ibm1130/ibm1130_cpu.c
In sim_instr(), the effective address is computed; for the case of TAG (index register addressing), the contents of the specified index register is added to the effective address, but the result is not masked to 16 bits as per the hardware functionality.
Adding a a 16 bit mask operation fixes the issue.
=> IBM1130: Fix address computation overflow

.travis/deps.sh, AltairZ80/CMakeLists.txt, Ibm1130/CMakeLists.txt, PDP10/CMakeLists.txt, VAX/CMakeLists.txt, makefile
- zlib now needs to be an explicit HomeBrew dependency. Previously, Apple distributed zlib as part of macOS. That is no longer the case.
- CMake: Periodic `generate.py` to update simulator `CMakeLists.txt` build files.
- PDP-10: Not entirely clear to me how/when `AIO_CCFLAGS` went missing (which causes `generate.py` to add `USES_AIO` to the CMake `add_simulator` arguments. Without AIO, the PDP-10 simulator users get a warning message with respect to AIO and networking.
=> macOS-12 CI/CD failure fix, periodic CMake regenerate

display/sim_ws.c
The "error" that the original change "fixed" was actually in the cmake build system and not in the sim_ws.c code.
The Uint8 type is specific to SDL2 APIs.
This is now rebased on the cmake fixes so the CI/CD builds should run cleanly.
=> Revert "Compile fix: replaced Uint8 by uint8."

sim_video.c
Fixes oversite of missing sim_video stub function.
=> VIDEO: Add vid_render_set_logical_size() stub

cmake/pthreads-dep.cmake
Currently when building with msys2 in a clang64 environment, cmake tries to use pthreads4w and fails. This restricts the compiler check to clang-cl only so mingw64 clang environments aren't affected.
=> Allow msys2 clang64 to compile with cmake

VAX/vax630_io.c, VAX/vax_io.c
Fixes issue #409 
Ultrix-32M v1.2 has a hardcoded bdp value (buffered data path) or'd into the memory address sent to an MSCP device. The memory address is subsequently used as a destination for the disk read, but since it is outside of the memory range, the device reports an I/O error causing the OS to fail.
This patch masks all QBus transfer addresses to 22 bits which allows Ultrix-32M v1.2 to install and run correctly.
=> VAX: Mask QBus addresses to 22 bits

.travis/deps.sh, README-CMake.md
Adds MacPorts as an option in the travis/deps.sh
=> Add macports support

AltairZ80/altairz80_cpu.c
HEX file loader "load -h <filename> ROM" will mark the pages as ROM.
=> AltairZ80: Adds "ROM" option to "load -h"

.github/workflows/cmake-builds.yml
Update maOS the macos-14 runner name to macos-latest. Reduce the runner's output when dealing with the leftover Python3 artifacts in /usr/local.
Add the ubuntu-latest runner to the Ubuntu matrix.
=> Github: Update runner names

tt2500/tt2500_cpu.c, tt2500/tt2500_dpy.c, tt2500/tt2500_tv.c, tt2500/tt2500_uart.c
- Debug: Output the character received, if printable.
- Eliminate type slicing warnings (uint32 -> uint16)
=> TT2500: Debugging and reduce type slice warnings.

sigma/sigma_coc.c
Fix sigma_coc.c to return CC=0 when line has disconnected. This problem was reported as issue #12 on kenrector/Sigma-cpv-kit concerning line hung after telnet quit.
=> sigma: return corrrect CC on line disconnect

H316/h316_hi.c, H316/h316_imp.h
This adds the modifiers CONVERT and NOCOVERT to the HI units.  When enabled for a unit, 1822 messages will transparently be converted.  IMP-to-host messages are converted from the old, short (32-bit) format to the new, long (96-bit) format.  Host-to-IMP messages are converted in the other direction.
The motivation for this feature, is that the currently running IMP software is from 1974 and only supports short leaders.  Some operating systems are from a later era, and only support long leaders.
This has been tested using the H316 emulator and the IMP code in the H316/test directory, and ITS running on a PDP-10 KA10 emulator.  I have also written a new NCP implementation that can be used to probe and test the network and hosts; it has successfully ran TELNET sessions in both directions …
=> H316: Convert IMP short leaders to long, and vice versa.

PDP11/pdp11_rh.c
On 7/31/2025 Bob Supnik wrote:
Yeah, good catch. I checked the RH11 and RH70 schematics, and WC is built out of four-bit cascaded counters that either lack a CLEAR pin or have it wired to ground (off).
=> PDP11: MASSBUS controller clear vs rhwc register

PDP11/pdp11_cpumod.c
=> PDP11: Fix typo in SYSTEM DR register description
